apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlineboutique
  namespace: onlineboutique
spec:
  releaseName: onlineboutique
  chartRef:
    kind: OCIRepository
    name: onlineboutique
  interval: 50m
  install:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["spec/replicas"]
        target:
          kind: Deployment
  # Default values
  # https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/helm-chart/values.yaml
  values:
    networkPolicies:
      create: true
    frontend:
      # Using ingress in favor of service type LoadBalancer
      externalService: false
      platform: aws