---
apiVersion: v1
kind: Namespace
metadata:
  name: wiz-admission-controller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: wiz-sec
  namespace: wiz-admission-controller
spec:
  interval: 24h
  url: https://charts.wiz.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wiz-admission-controller
  namespace: wiz-admission-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: wiz-admission-controller
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: wiz-sec
        namespace: wiz-admission-controller
      interval: 12h
  values:
    replicaCount: 1
    wizApiToken:
      secret:
        create: false
        # Steps to create this secret:
        # Open Wiz. Settings > Access Management > Service Accounts > Add Service Account type Kubernetes Admission
        # Save values then run:
        # k create secret generic wiz-client-auth --from-literal=clientId=VALUE --from-literal=clientToken=VALUE -n wiz-admission-controller
        name: "wiz-client-auth"
    kubernetesAuditLogsWebhook:
      enabled: true
      replicaCount: 1
    opaWebhook:
      namespaceSelector:  # https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
        matchExpressions:
        - key: kubernetes.io/metadata.name # Using "kubernetes.io/metadata.name" key to exclude specific namespaces (https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2161-apiserver-default-labels/README.md#proposal)
          operator: NotIn
          values:
          - kube-system
          - kube-node-lease
          - wiz-admission-controller
          - wiz-sensor