apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/wiz-admission-controller
  - wiz-admission-controller-auth-secret.yaml
  - ../base/wiz-sensor
  - wiz-sensor-auth-secret.yaml
  - wiz-sensor-image-pull-auth-secret.yaml
spec:
  decryption:
    provider: sops