apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tnycum-basic-cluster
  region: us-east-1
  version: "1.29"

autoModeConfig:
  enabled: true

iam:
  withOIDC: true
  # eksctl utils associate-iam-oidc-provider --config-file=eks/cluster.yaml --name kustomize-controller --attach-role-arn=<role-arn>
  # or...
  # serviceAccounts:
  # - metadata:
  #     name: kustomize-controller
  #     namespace: flux-system
  #   attachPolicyARNs:
  #   - "arn:aws:iam::aws:policy/TODO" # TODO