---
apiVersion: v1
kind: Namespace
metadata:
  name: aws
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-lb-controller
  namespace: aws
spec:
  interval: 24h
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-lb-controller
  namespace: aws
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: aws-lb-controller
        namespace: aws
      interval: 12h
  values:
    clusterName: myCluster # TODO
    serviceAccount:
      create: false
      name: aws-load-balancer-controller