apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: game-2048
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - networkpolicy.yaml