apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wiz-kubernetes-integration
  namespace: wiz
spec:
  interval: 30m
  chart:
    spec:
      chart: wiz-kubernetes-integration
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: wiz-sec
        namespace: wiz
      interval: 12h
      reconcileStrategy: Revision
  values:
    global:
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token
      
    wiz-sensor:
      enabled: true
      imagePullSecret:
        create: false
        name: sensor-image-pull

    wiz-admission-controller:
      enabled: true
      opaWebhook:
        enabled: true
      kubernetesAuditLogsWebhook:
        enabled: true