apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ado-agent
  namespace: ado
spec:
  values:
    replicaCount: 1
    maxReplicas: 3
    pipelines:
      cleanup:
        failed: 10
        successful: 10