apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ado-agent
  - ado-agent-auth-secret.yaml
patches:
  - path: ado-agent-values.yaml
    target:
      kind: HelmRelease